// gdat_to_ld.c
//  This program will take in a gdat file generated by the DLM and
//  convert it to a .ld file that can be read in I2. Data that comes
//  out will not match exactly as gdat stores data with a timestamp
//  attached and does not need to be a consistant frequency, but I2
//  data does need to be

#include "gdat_to_ld.h"
#include "ld_writing.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


// define everything that is neede in static memory
START_OF_FILE_t sof_data = {0};
FILE_METADATA_t file_data = {0};

// the head node WILL NOT be written in memory so it do not count it
CHANNEL_DESC_LL_NODE_t channel_head = 
{
    .channel_desc = {0},
    .location_fptr = 0,
    .data_buffer = NULL,
    .prev = NULL,
    .next = NULL,
};


int main(int argc, char** argv)
{
    
    // fill in all of the names and metadata for the ld file. This includes the
    // date and time from the gdat file, as well as event name, session, comments,
    // and location
    // TODO

    // read in the gdat file and store all the data in ram with some linked
    // lists for all of the data nodes. Do some fancy math to figure out what
    // the offset, scaler, divisor, and base10_shift should be. Also find the
    // logging frequency
    // TODO

    // take the data from gdat and use it to fill in all of the ld data headers
    // and data buffers. This will not fill in the pointers yet
    // TODO

    // DEBUG filling in the sof and metadata
    init_sof_block(&sof_data, 2022, 3, 30, 4, 20, 55, "SESSION", "SHORT COMMENT", "TEAM NAME");
    init_metadata_block(&file_data, "EVENT NAME", "SESSION", "LONG COMMENT", "LOCATION");

    // DEBUG add a couple of data points for testing
    // Doing 100 data points at 10 Hz
    U32 buf1[100];
    U32 buf2[100];
    U32 buf3[1000];
    for (int c = 0; c < 100; c++)
    {
        buf1[c] = c;
        buf2[c] = 100 - c;
    }

    for (int c = 0; c < 1000; c++) buf3[c] = c;
    add_channel_to_list(&channel_head, 100, buf1, 10, 0, 1, 1, 1, "GPS Latitude", "GPSLat", "deg");
    add_channel_to_list(&channel_head, 100, buf2, 10, 0, 1, 1, 1, "GPS Longitude", "GPSLong", "deg");
    add_channel_to_list(&channel_head, 1000, buf3, 100, 0, 1, 1, 2, "tester variable 3", "test3", "unit3");

    // Run the "linker". This will fill out correct file space for all of the different
    // blocks of data and makes sure they will be correctly pointed to in the file
    if (link_id_file(&sof_data, &file_data, &channel_head)) return -1;

    // Open a new file with the correct name and begin writing all of the data to it.
    // Layout the file as planned after the linker was run
    if (write_id_file(&sof_data, &file_data, &channel_head, "test_ld.ld")) return -1;

    printf("Conversion sucessful\n");
}

